version: 2

jobs:
  deploy:
    docker:
      - image: felicianotech/docker-hugo:latest
    steps:
      - checkout
      - run:
          name: Deploy
          command: ./scripts/deploy.sh

workflows:
  version: 2
  lint_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: 
                - master
